from enum import Enum
from binance.client import Client


class CryptoSymbols(Enum):
    BTCUSDT = "BTCUSDT"
    ETHUSDT = "ETHUSDT"
    AVAXUSDT = "AVAXUSDT"
    SOLUSDT = "SOLUSDT"
    RENDERUSDT = "RENDERUSDT"
    FETUSDT = "FETUSDT"


class KlineIntervals(Enum):
    T1SECOND = Client.KLINE_INTERVAL_1SECOND
    T1MINUTE = Client.KLINE_INTERVAL_1MINUTE
    T3MINUTE = Client.KLINE_INTERVAL_3MINUTE
    T5MINUTE = Client.KLINE_INTERVAL_5MINUTE
    T15MINUTE = Client.KLINE_INTERVAL_15MINUTE
    T30MINUTE = Client.KLINE_INTERVAL_30MINUTE
    T1HOUR = Client.KLINE_INTERVAL_1HOUR
    T2HOUR = Client.KLINE_INTERVAL_2HOUR
    T4HOUR = Client.KLINE_INTERVAL_4HOUR
    T6HOUR = Client.KLINE_INTERVAL_6HOUR
    T8HOUR = Client.KLINE_INTERVAL_8HOUR
    T12HOUR = Client.KLINE_INTERVAL_12HOUR
    T1DAY = Client.KLINE_INTERVAL_1DAY
    T3DAY = Client.KLINE_INTERVAL_3DAY
    T1WEEK = Client.KLINE_INTERVAL_1WEEK
    T1MONTH = Client.KLINE_INTERVAL_1MONTH
